services:
  postgres:
    image: postgres:15
    container_name: cqrs_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cqrs_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: